version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: cubadev
      POSTGRES_PASSWORD: LS920UL3
      POSTGRES_DB: cubaDB
  web:
    build: .
    command: bash run.sh     
    ports:
      - "8000:8000"
    depends_on:
      - db
